### ISSUE TITLE
Update aesxor.cc

### ISSUE THREAD

**Issue by bryongloden** [paypal/seifnode#23]
[[../seifnode-master/src/aesxor.cc:91](https://github.com/paypal/seifnode/blob/master/src/aesxor.cc#L91)]: (error) Shifting 32-bit value by 56 bits is undefined behavior

Found by https://github.com/bryongloden/cppcheck

**Comment by aashish-sheshadri** [comment]
@bryongloden, Thanks for running cppcheck! The function that the check is complaining about is an internal helper that converts 64bit numbers to bytes. Since its only being used internally, we expect the function to not deal with 32bit numbers. But strictly speaking yes we can make sure that we only process if the iterator is pointing to a int64 value type.
