### ISSUE TITLE
Is Seif dead?

### ISSUE THREAD

**Issue by shofetim** [paypal/seifnode#33]
I don't see any new commits, presentations, website updates etc.

**Comment by douglascrockford** [comment]
No, it is not dead.

**Comment by patrickmichalina** [comment]
Is there a roadmap or other information? A gitter chat perhaps?

**Comment by douglascrockford** [comment]
I think it is done.

**Comment by shofetim** [comment]
Not to be too much of a pain, but _what_ is done? The protocol? The Node implementation? The Qt based browser extension/sandbox/runtime?

or is that "done" in it is as far as you want to take it?

For what it is worth, I think the ideas are spot on, but there hasn't been a way to help bring them to fruition, and I didn't want to build a competing implementation.

**Comment by wirelessben** [comment]
I hear you, Jordan. I had high hopes as well. Gave a couple presentations.
Even pinged the Firefox-dev list last year for their take, but they weren't
interested in redoing the web.

Seems like someone would want to be _the secure browser_. DoD and banks
would be customers.

Trust management seems to be a big hurdle. I was expecting a
blockchain-based trust system to replace DNS.

The reason I jumped on seif was because it solved the fundamental problem
of the web: that TBL implemented http as a stateless protocol, with all the
security problems inherent in that decision. Marcus Ranum talked about this
in his brilliant Internet Nails talk from 2010 (on YouTube). So http
inherits state from tcp _and throws it away_.

Maybe the three letter agencies have already invented a seif-based browser
and forgot to tell us? No, they really like being able to evesdrop on
everyone, so ... Next!

I don't know where we go from here. IPFS? Maybe you _should_ pick up the
seif protocol and build something we can use.

Ben

**Comment by patrickmichalina** [comment]
@wirelessben thanks for your feedback. I was so happy to learn about this project back in 2015 at the AngularU conference. Been checking back in since then and noticed commits have stopped to these repos and no other layer of seif has been started (at least publicly).

This is disheartening. I was rolling up my sleeves to get started with prototypes on seif-protocol. Any rationale for the ending of the project? Is there a security issue or philosophical issue discovered with the ideas presented in seif?

**Comment by douglascrockford** [comment]
I was unable to find the funding to complete it.

**Comment by shofetim** [comment]
Douglas,

Thank you taking the time to respond. I think it would be a long shot for the community to complete it, but I for one am interested in the undertaking.

**Comment by riccardomariani** [comment]
@douglascrockford @shofetim 
Me too, you can count on me as well ;-) on both node and java side.
I think this community could grow quickly.

**Comment by wirelessben** [comment]
Since when has money been the determining factor to open source?

Here we have two developers and a sysadmin (me) willing to find time to
work on this project. Let's do it.

Things to do:

Define what right looks like. I'm thinking of the browser experience. So
you're browsing the web as normal and Brian Krebs says check out
https://someseifsite.org. You click the link and what happens?

1. The page focuses on the green lock icon and says you're really not safe.
The enessay is listening, Facebook is hacked, yada yada. Try this plugin:
https://seif.org/plugin. The site has plugins for Chrome, Firefox, Safari,
Edge.

2. You install the plugin. Suddenly a new web opens up. A safe web. You see
seif links to some very safe names like MIT and Stanford and Wells Fargo*.

3. The green lock icon changes to yellow to signify the old web. A
notification points this out and directs you to one of these seif links.
Now you get a green lock again and a notification explaining why you see
green again. (This is a Stanford site. The web of trust verifies this. All
these institutions verify this site: MIT, Wells Fargo, etc.)

4. Now you can browse safely. Have a good day.

Am I making sense? It's not about the money. Apache was developed by people
who all had other jobs. This project is the definition of "a few motivated
individuals changing the world".

We can do this. Are you with us, Douglas?

Ben

* Intentional. Who is more interested in reviving trust in their name than
Wells Fargo? That translates into money for the project.

**Comment by patrickmichalina** [comment]
With some cleanup (typescript based, RXJS, etc) I think the node/server layer of the system can prove to be an easy way for devs to spin up servers and start creating services. It would be prudent to port this over from Node to [deno](https://github.com/denoland/deno) to have better runtime security from the start (although deno is early stages).

Trust management and GUI tech would be the last bit that needed. I don't think the browser plugin is as important. An app with something like QT (or better) is probably going to run faster than having it run inside chrome/firefox etc. Also, if it were to be running in the browser anyway, why not just use HTML as the UI layer? I remember HTML was ditched in design cause its not app-centric and its not secure. So why the browser plugin at all?

**Comment by wirelessben** [comment]
Ah, you're a middleware guy.

>So why the browser plugin at all?

I'm looking at adoption through the browser's lens because that's how
almost all people are impacted. I suppose all this could happen in the
background and users wouldn't care how the browser got the content. That
_is_ the promise of a content-based internet (get me the latest political
news) over the location-based internet of today
(serverIP:/path/to/document).

>Also, if it were to be running in the browser anyway, why not just use
HTML as the UI layer?

That's fine with me. Douglas is the expert, of course.
